### ISSUE TITLE
Setup codefresh on kubernetes cluster.

### ISSUE THREAD

**Issue by nishit93-hub** [vfarcic/codefresh-cli#1]
@vfarcic

 Can we set up Codefresh on Kubernetes to use and manage our own? If we don't want to use their trial or paid version.

**Comment by vfarcic** [comment]
I don't think there is such an option with the old Codefresh (the one I used in this example). Since then, Codefresh moved towards adopting Argo Workflows (and the rest of Argo projects) so it should look very different now. However, I haven't been following it closely for a while now so I don't know the exact status or the transition to Argo.

**Comment by nishit93-hub** [comment]
@vfarcic Ok Thanks.

**Comment by nishit93-hub** [comment]
@vfarcic One more question

I have set up the Git SCM on k8s using the `ubuntu` docker image and making the `mount path ` as a bare repo. I am looking for a UI tool for Git SCM which I can use on k8s.

Is there any tool in your knowledge I can use?

**Comment by vfarcic** [comment]
Unfortunately, I never tried any of Git GUI tools so I cannot recommend any. I prefer running `git` commands directly from a terminal and, if I would be looking for a GUI that would probably be a plugin in VSCode.
